version: "3.8"
services:
  api-gateway:
    volumes:
      - ./config.yaml:/api-gateway/config.yaml
    build: ./api-gateway
    ports:
      - "4040:4040"
    depends_on:
      - budget-service
      - income-service
      - user-service
      - report-service
      - notification-service
    environment:
      - BUDGET_SERVER_HOST=budget-service
      - BUDGET_SERVER_PORT=5050
      - INCOME_SERVER_HOST=income-service
      - INCOME_SERVER_PORT=6060
      - USER_SERVER_HOST=user-service
      - USER_SERVER_PORT=7070
      - REPORTING_SERVER_HOST=report-service
      - REPORTING_SERVER_PORT=9090
      - KAFKA_BROKER=kafka:9092  # Kafka broker ulanishi to'g'ri sozlandi
    networks:
      - mynetwork

  budget-service:
    build: ./budget-service
    ports:
      - "5050:5050"
    depends_on:
      - postgres
      - redis
    networks:
      - mynetwork

  income-service:
    build: ./income-service
    ports:
      - "6060:6060"
    depends_on:
      - postgres
      - redis
    networks:
      - mynetwork

  report-service:
    build: ./report-service
    ports:
      - "9090:9090"
    depends_on:
      - budget-service
      - income-service
    networks:
      - mynetwork

  user-service:
    build: ./user-service
    ports:
      - "7070:7070"
    depends_on:
      - postgres
      - redis
    networks:
      - mynetwork

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vakhaboff
      - POSTGRES_DB=mydatabase
    ports:
      - "5433:5432"
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092  # Kafka broker ichki ulanish uchun
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - mynetwork
    restart: on-failure

  notification-service:
    build: ./notification-service
    ports:
      - "8080:8080"
      - "2020:2020"
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092  
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
