// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: protos/reporting/reporting.proto

package reporting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetIncomeExpenseReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetIncomeExpenseReportRequest) Reset() {
	*x = GetIncomeExpenseReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_reporting_reporting_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIncomeExpenseReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncomeExpenseReportRequest) ProtoMessage() {}

func (x *GetIncomeExpenseReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_reporting_reporting_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncomeExpenseReportRequest.ProtoReflect.Descriptor instead.
func (*GetIncomeExpenseReportRequest) Descriptor() ([]byte, []int) {
	return file_protos_reporting_reporting_proto_rawDescGZIP(), []int{0}
}

func (x *GetIncomeExpenseReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IncomeExpenseReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalIncome   float64 `protobuf:"fixed64,1,opt,name=totalIncome,proto3" json:"totalIncome,omitempty"`
	TotalExpenses float64 `protobuf:"fixed64,2,opt,name=totalExpenses,proto3" json:"totalExpenses,omitempty"`
	NetSavings    float64 `protobuf:"fixed64,3,opt,name=netSavings,proto3" json:"netSavings,omitempty"`
}

func (x *IncomeExpenseReportResponse) Reset() {
	*x = IncomeExpenseReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_reporting_reporting_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncomeExpenseReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomeExpenseReportResponse) ProtoMessage() {}

func (x *IncomeExpenseReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_reporting_reporting_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomeExpenseReportResponse.ProtoReflect.Descriptor instead.
func (*IncomeExpenseReportResponse) Descriptor() ([]byte, []int) {
	return file_protos_reporting_reporting_proto_rawDescGZIP(), []int{1}
}

func (x *IncomeExpenseReportResponse) GetTotalIncome() float64 {
	if x != nil {
		return x.TotalIncome
	}
	return 0
}

func (x *IncomeExpenseReportResponse) GetTotalExpenses() float64 {
	if x != nil {
		return x.TotalExpenses
	}
	return 0
}

func (x *IncomeExpenseReportResponse) GetNetSavings() float64 {
	if x != nil {
		return x.NetSavings
	}
	return 0
}

type GetSpendingByCategoryReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetSpendingByCategoryReportRequest) Reset() {
	*x = GetSpendingByCategoryReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_reporting_reporting_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpendingByCategoryReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpendingByCategoryReportRequest) ProtoMessage() {}

func (x *GetSpendingByCategoryReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_reporting_reporting_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpendingByCategoryReportRequest.ProtoReflect.Descriptor instead.
func (*GetSpendingByCategoryReportRequest) Descriptor() ([]byte, []int) {
	return file_protos_reporting_reporting_proto_rawDescGZIP(), []int{2}
}

func (x *GetSpendingByCategoryReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CategorySpending struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category   string  `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	TotalSpent float64 `protobuf:"fixed64,2,opt,name=totalSpent,proto3" json:"totalSpent,omitempty"`
}

func (x *CategorySpending) Reset() {
	*x = CategorySpending{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_reporting_reporting_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategorySpending) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategorySpending) ProtoMessage() {}

func (x *CategorySpending) ProtoReflect() protoreflect.Message {
	mi := &file_protos_reporting_reporting_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategorySpending.ProtoReflect.Descriptor instead.
func (*CategorySpending) Descriptor() ([]byte, []int) {
	return file_protos_reporting_reporting_proto_rawDescGZIP(), []int{3}
}

func (x *CategorySpending) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CategorySpending) GetTotalSpent() float64 {
	if x != nil {
		return x.TotalSpent
	}
	return 0
}

type SpendingByCategoryReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spending []*CategorySpending `protobuf:"bytes,1,rep,name=spending,proto3" json:"spending,omitempty"`
}

func (x *SpendingByCategoryReportResponse) Reset() {
	*x = SpendingByCategoryReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_reporting_reporting_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpendingByCategoryReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendingByCategoryReportResponse) ProtoMessage() {}

func (x *SpendingByCategoryReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_reporting_reporting_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendingByCategoryReportResponse.ProtoReflect.Descriptor instead.
func (*SpendingByCategoryReportResponse) Descriptor() ([]byte, []int) {
	return file_protos_reporting_reporting_proto_rawDescGZIP(), []int{4}
}

func (x *SpendingByCategoryReportResponse) GetSpending() []*CategorySpending {
	if x != nil {
		return x.Spending
	}
	return nil
}

var File_protos_reporting_reporting_proto protoreflect.FileDescriptor

var file_protos_reporting_reporting_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x69,
	0x6e, 0x67, 0x2f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x37, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x45,
	0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x85, 0x01, 0x0a, 0x1b,
	0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x24, 0x0a,
	0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x45, 0x78, 0x70, 0x65, 0x6e,
	0x73, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x65, 0x74, 0x53, 0x61, 0x76, 0x69, 0x6e, 0x67,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x6e, 0x65, 0x74, 0x53, 0x61, 0x76, 0x69,
	0x6e, 0x67, 0x73, 0x22, 0x3c, 0x0a, 0x22, 0x47, 0x65, 0x74, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x42, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x4e, 0x0a, 0x10, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x53, 0x70, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x70, 0x65, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x70, 0x65, 0x6e,
	0x74, 0x22, 0x51, 0x0a, 0x20, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x79, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x73, 0x70, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x32, 0xd1, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x69,
	0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x56, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x1e, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x45,
	0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x45, 0x78, 0x70, 0x65,
	0x6e, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x65, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x42, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x23, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x79,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x42, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x72, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_reporting_reporting_proto_rawDescOnce sync.Once
	file_protos_reporting_reporting_proto_rawDescData = file_protos_reporting_reporting_proto_rawDesc
)

func file_protos_reporting_reporting_proto_rawDescGZIP() []byte {
	file_protos_reporting_reporting_proto_rawDescOnce.Do(func() {
		file_protos_reporting_reporting_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_reporting_reporting_proto_rawDescData)
	})
	return file_protos_reporting_reporting_proto_rawDescData
}

var file_protos_reporting_reporting_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_reporting_reporting_proto_goTypes = []any{
	(*GetIncomeExpenseReportRequest)(nil),      // 0: GetIncomeExpenseReportRequest
	(*IncomeExpenseReportResponse)(nil),        // 1: IncomeExpenseReportResponse
	(*GetSpendingByCategoryReportRequest)(nil), // 2: GetSpendingByCategoryReportRequest
	(*CategorySpending)(nil),                   // 3: CategorySpending
	(*SpendingByCategoryReportResponse)(nil),   // 4: SpendingByCategoryReportResponse
}
var file_protos_reporting_reporting_proto_depIdxs = []int32{
	3, // 0: SpendingByCategoryReportResponse.spending:type_name -> CategorySpending
	0, // 1: ReportingService.GetIncomeExpenseReport:input_type -> GetIncomeExpenseReportRequest
	2, // 2: ReportingService.GetSpendingByCategoryReport:input_type -> GetSpendingByCategoryReportRequest
	1, // 3: ReportingService.GetIncomeExpenseReport:output_type -> IncomeExpenseReportResponse
	4, // 4: ReportingService.GetSpendingByCategoryReport:output_type -> SpendingByCategoryReportResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_reporting_reporting_proto_init() }
func file_protos_reporting_reporting_proto_init() {
	if File_protos_reporting_reporting_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_reporting_reporting_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetIncomeExpenseReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_reporting_reporting_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*IncomeExpenseReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_reporting_reporting_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetSpendingByCategoryReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_reporting_reporting_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CategorySpending); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_reporting_reporting_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*SpendingByCategoryReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_reporting_reporting_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_reporting_reporting_proto_goTypes,
		DependencyIndexes: file_protos_reporting_reporting_proto_depIdxs,
		MessageInfos:      file_protos_reporting_reporting_proto_msgTypes,
	}.Build()
	File_protos_reporting_reporting_proto = out.File
	file_protos_reporting_reporting_proto_rawDesc = nil
	file_protos_reporting_reporting_proto_goTypes = nil
	file_protos_reporting_reporting_proto_depIdxs = nil
}
